Hw4
ivanyshenko/scala-school pull request #4
Opened 2017-04-23 14:04 UTC by ivanyshenko

2017-04-26 22:56 UTC, vatt2001 requested changes

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    addresses.take(couriers.filter(_ => traffic().degree < 5).foldLeft(0)((acc, c) => acc + c.canServe ))
`foldLeft` можно заменить на просто `map(_.canServe).sum`

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/collections/comprehension/Couriers.scala
> +    serveAddresses(addresses, couriers).map(a => println(a.postIndex))
Лучше не map, а foreach, так как основная суть здесь - это сайд эффект. map же используется для преобразования без сайд эффектов (особенно больно это бывает, когда в качестве коллекции у тебя выступает View)

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +//  val authenticated: List[Option[User]] = {
А это чем помешало, зачем закомментил? )

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +    addImpl(newValue, Option(this)).get
1. Зачем у тебя второй параметр всегда обернут в Option?
2. `Option.get` считается дурным тоном, потому что ты, фактически, всегда игнорируешь второй случай, когда там ничего нет.

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +      if (node.isEmpty) Option(null)
`Option(null) == None`

2017-04-26 22:56 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +   override def toString() = {
Это точно работает? Как минимум, не увидел здесь переводы строк (каждый уровень дерева должен быть на собственной строке).

2017-04-26 22:56 UTC, vatt2001 commented on src/test/scala/lectures/matching/SortingStuffGeneratorBasedTest.scala
> +      "was occasionally disposed" in {
Здесь и ниже: когда пишешь тесты с применением генераторов, то надо использовать `forAll(myGenerator) { ... }`

2017-04-29 09:08 UTC, ivanyshenko commented on src/main/scala/lectures/functions/Authentication.scala
> +//  val authenticated: List[Option[User]] = {
Потому что данная функция использовала testUsers, а их в другом задании просили закомментить. Этот метод все равно использовался вместо теста и в данный момент не нужен.

2017-04-29 09:10 UTC, ivanyshenko commented on src/main/scala/lectures/oop/BST.scala
> +   override def toString() = {
я просто слева направо распечатываю все элементы дерева. Конкретных требований к распечатыванию дерева не было, я и не думал долго.

2017-04-29 09:39 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +   override def toString() = {
В лекциях был пример, как именно надо распечатывать (см слайд 86). Аналогичное задание было среди вступительных.

2017-05-03 12:03 UTC, merged